import java.util.Scanner;

public class ProfitLoss{
	public static void main(String[] args){
		Scanner sc = new Scanner(System.in);
		float cost, sell;
		double profit;
		System.out.println("Enter Cost Price and Sell Price :");
		cost = sc.nextFloat();
		sell = sc.nextFloat();
		profit=sell-cost;
		if(sell>cost){
					System.out.println("Seller made profit");
					System.out.println("Profit generated by seller is "+profit);
		}else if(sell<cost){
					System.out.println("Seller made loss  Seller does not make any profit");
			}else{
				System.out.println("Seller Does not make any profit Not have a loss");
		}
		
	}
}